### ISSUE TITLE
Better signaling of rate limit hits

### ISSUE THREAD

**Issue by Xion** [softprops/hubcaps#103]
Currently, the only way to recognize we've hit the API rate limit is to match on `Error::(ErrorKind::Fault{message, ..}, _))` and do some fragile string recognition against the content of `error.message`.

I suggest a new `ErrorKind` be introduced for this case, and have it contain the value of `X-RateLimit-Limit` that was exceeded. (It would be great to also have access to `X-RateLimit-Remaining` from successful requests, but that's a separate issue).

**Comment by softprops** [comment]
This former is very doable. The latter would require a bigger breaking change. This crate uses the log crate and logs response headers if you are trying to learn how close you are getting. I'll look into the new error kind and improving the header logging

**Comment by softprops** [comment]
Just published a new version. Let me know if this interface feels right

**Comment by Xion** [comment]
This is neat. With `reset`, I should be able to eventually implement proper back-off and eliminate rate limit errors entirely from user's PoV.

Thanks!

**Comment by softprops** [comment]
Excellent. Let me know if this works well in practice
