### ISSUE TITLE
Provide possibility to use conditional requests (using ETag)

### ISSUE THREAD

**Issue by globin** [softprops/hubcaps#104]
It would be nice to be able to supply an `If-None-Match` or `If-Modified-Since` header and receive `ETag` and `Last-Modified` headers in order to avoid hitting the rate limit too fast.

See https://developer.github.com/v3/#conditional-requests

**Comment by softprops** [comment]
This could be cool. I'd have to think about how I could integrate this functionality without changing existing interfaces heavily. One potential I can think of is to leverage hyper's client connector to capture known etag content mappings and manage the conditional cache transparently ( much like browsers ). I'll investigate the options.

**Comment by dwijnand** [comment]
> I'll investigate the options.

Let me know if you found anything, as I'm looking to tackle this.

**Comment by softprops** [comment]
I actually think the best option would not to implement etagging here but to implement it as an extension of hyper ( as a connector ) and provide that to hubcaps via the [Github::custom](https://docs.rs/hubcaps/0.4.8/hubcaps/struct.Github.html#method.custom) constructor that takes a raw hyper client. Having this in another create would technically allow anyone writing a client on top of hyper ( i.e. the whole rust ecosystem :) ) to be able to reuse it.

**Comment by dwijnand** [comment]
Here is my WIP.

I started work on this (really early day experiments in https://github.com/softprops/hubcaps/compare/master...dwijnand:conditional_requests).

I found out an implementation which I assume is reasonably complete deep inside Servo: https://github.com/servo/servo/blob/master/components/net/http_cache.rs

I also found `static_http_cache`, which is independent and, while built for the `reqwest` library, supposedly supports alternative http backends: https://docs.rs/static-http-cache/0.1.0/static_http_cache/index.html#alternative-http-backends

**Comment by dwijnand** [comment]
> Although `static_http_cache` is designed to work with the `reqwest` library, it will accept any type that implements the traits in the `reqwest_mock` module.

Because of coherence it's not possible to define implementation of `reqwest_mock` traits for `hyper`. So that's a showstopper there.

And it looks complicated to depend on servo or some subset of servo's components.

So I guess I'll start implementing my own? 😕

**Comment by softprops** [comment]
Nice finds. I feel like a hyper native impl would serve the widest audience

**Comment by dwijnand** [comment]
I'll see what I can do.

**Comment by dwijnand** [comment]
So with the hyper 0.12 upgrade landing here I've looked at this again and I don't think this can be done with hyper connectors.

[Connect](https://docs.rs/hyper/0.12.9/hyper/client/connect/trait.Connect.html) takes a [Destination](https://docs.rs/hyper/0.12.9/hyper/client/connect/struct.Destination.html) which only has scheme/host/port. We need path, method, headers, etc. It's the wrong level of abstraction.

**Comment by dwijnand** [comment]
Seeing as this is not hubcaps specific (as you said: "Having this in another create would technically allow anyone writing a client on top of hyper ( i.e. the whole rust ecosystem :) ) to be able to reuse it."), so I've opened a ticket in hyper: https://github.com/hyperium/hyper/issues/1647
