### ISSUE TITLE
IssueListOptions State::All seems not to work

### ISSUE THREAD

**Issue by matthiasbeyer** [softprops/hubcaps#113]
I'm not sure about this, but it seems that `State::All` does only list open issues.

When importing the [imag](https://github.com/matthiasbeyer/imag) repository with https://github.com/matthiasbeyer/git-dit-github-import/, I get ~20 issues imported, but it should be ~400.

**Comment by softprops** [comment]
Many collections apis have a list method that returns a vec of the first page of results and a iter method that returns a stream over all results. Issues is missing iter http://lessis.me/hubcaps/hubcaps/issues/struct.Issues.html. I'll try and add that in the next release

**Comment by softprops** [comment]
covered this in [here](https://github.com/softprops/hubcaps/pull/114/files) updated the [issues example](https://github.com/softprops/hubcaps/blob/master/examples/issues.rs#L29-L36) to draw a picture of how to use the new interface

**Comment by softprops** [comment]
@matthiasbeyer this is now published in 0.4.5
