### ISSUE TITLE
Issue getting teams example to compile

### ISSUE THREAD

**Issue by dalen** [softprops/hubcaps#120]
I'm a bit of a rust newbie still, but I'm having issues compiling the `teams.rs` example:

```
error: the `for_each` method cannot be invoked on a trait object
  --> src/main.rs:33:22
   |
33 |                     .for_each(|team| Ok(println!("{:#?}", team))),
   |                      ^^^^^^^^
help: another candidate was found in the following trait, perhaps add a `use` for it:
   |
8  | use futures::stream::Stream;
   |

error: the `for_each` method cannot be invoked on a trait object
  --> src/main.rs:41:22
   |
41 |                     .for_each(|team| Ok(println!("{:#?}", team))),
   |                      ^^^^^^^^
help: another candidate was found in the following trait, perhaps add a `use` for it:
   |
8  | use futures::stream::Stream;
```

The suggestion of adding `use futures::stream::Stream;` does not help.

**Comment by dalen** [comment]
Was actually able to fix this by specifying that it should use futures 0.1.x, it got defaulted to 0.2.x.

**Comment by softprops** [comment]
This crate depends on futures 0.1 for the time being. The 0.2 line of the futures crate as I understand is still in flux and likely to change often. Until 0.2 stablizes I'm going to stick with 0.1 for now as it's apis are relatively stable
