### ISSUE TITLE
Feature: Installations API

### ISSUE THREAD

**Issue by phansch** [softprops/hubcaps#149]
See https://developer.github.com/v3/apps/installations/

And also retrieving an access token: https://developer.github.com/v3/apps/#create-a-new-installation-token

**Comment by phansch** [comment]
Going to start with the installation token.

**Comment by grahamc** [comment]
With the work in https://github.com/softprops/hubcaps/pull/178/files#diff-cca72d990dfd11d6b691180e03694f19R36 this should be easier now.

**Comment by softprops** [comment]
This should be covered now https://github.com/softprops/hubcaps/blob/master/examples/invitations.rs
