### ISSUE TITLE
Next minor release planning

### ISSUE THREAD

**Issue by softprops** [softprops/hubcaps#152]
Upgrading to a new version of hyper created an opportunity to revisit some design decisions from the past.

Something's I'd like to think about changing

Unify list/iter. In the past I've gotten much feedback about list methods being confusing and rightfully so as iter methods exist and list methods provide incomplete results ( just the first page ). Iter methods used to return iterator interfaces. This changed to streams when moving to asyn hyper. Calling iter and getting back a stream is not what you expect in rust. Let's consider unifying and have all list methods return a stream

Failure  > error chain. The community has shifted in the failure crates favor. Let's play nice with the community

**Comment by Marwes** [comment]
Any chance of a release soon? I'd like to avoid the `tokio-core` and old hyper dependency that the current release uses?

**Comment by softprops** [comment]
I'm splitting time between this and updating a  few other crates. I'll try to get this done soon. In the meantime if you are depending on hubcaps from an application instead of as a library you could depend on the latest via git https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories until I cut the new release

**Comment by dwijnand** [comment]
I've been wondering, before you commit to the public API if we should change `HttpCache` from being an `enum` to something extendable. To me "enum" implies some stable algebraic sum of types, like Some/None, Nil/::. In that sense I think `HttpCache` should just be a trait, and have a couple of impls..

I'll try and PR something tomorrow, if I can figure out the types/borrow-checking required.

**Comment by dwijnand** [comment]
Alternatively, is there some kind of convention for "this API may change/is not stable", like an attribute or something?

**Comment by softprops** [comment]
A cargo feature flag would be great

**Comment by softprops** [comment]
going to punt on the iter/list, error-chain changes for now.
