### ISSUE TITLE
feature flag http cache before releaseing 0.5

### ISSUE THREAD

**Issue by softprops** [softprops/hubcaps#167]
this feature is implemented but has potential room for changing. lets make this opt in by default until we start gaining some experience with it to allow for more change with less breakage

**Comment by softprops** [comment]
https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=Features#the--features--section

**Comment by dwijnand** [comment]
As mentioned in #152, I'm not sure how, in terms of API, to make it work.  As in, I understand defining a flag in the build, but in the API I wasn't sure how to make it opt-in.  Probably just inexperience.

**Comment by softprops** [comment]
@dwijnand no worries Im going to take a shot at this in https://github.com/softprops/hubcaps/pull/170/files
