### ISSUE TITLE
Break up Github::request 

### ISSUE THREAD

**Issue by dwijnand** [softprops/hubcaps#196]
`Github::request` is currently 253 lines long.

But how should it be broken up?  I was thinking by moving it to be a function in a new `request.rs` file and then breaking it into smaller functions.  Ideally, these could make use of `?` and `Result` to clean things up, but with things being futures perhaps that's not possible.

WDYT?

**Comment by softprops** [comment]
Triaging gh issues. Im still into this if you'd like to do this

**Comment by dwijnand** [comment]
I've moved on from Rust (no hard feelings at all, just shifted interests).

So I'll close it for lack of my own interests, but I understand if you want to reopen it for yourself.
