### ISSUE TITLE
Feature request: oauth

### ISSUE THREAD

**Issue by steveklabnik** [softprops/hubcaps#20]
This _might_ not be something you'd want in hubcaps proper, but it would be nice to be able to have some helper stuff around GitHub's oauth implementation. The use case here is a website with "log in via GitHub" that wants to use hubcaps for interacting with GitHub.

**Comment by softprops** [comment]
Fantastic idea. I've been using this with personal access tokens so far. I'll definitely have a look.

**Comment by softprops** [comment]
closing this. its a bit out of scope. this crate just assumes provisioning of tokens is provided at a higher level
