### ISSUE TITLE
Spurious stalling execution when retrieving issues and comments

### ISSUE THREAD

**Issue by mre** [softprops/hubcaps#201]
## 🐛 Bug description

I was testing hubcaps in this project: https://github.com/mre/rfcs

What I'm trying to do is read all issues from a Github repo and their accompanying comments.
The key part is here:

https://github.com/mre/rfcs/blob/master/src/github.rs#L35-L60

For some reason, this hangs after reading a few issues. I initially thought it was because of my [Github request quota](https://developer.github.com/v3/rate_limit/), but I checked and it doesn't look like I run into a rate limit.

Most likely this is an issue with my environment or my lack of understanding of tokio/futures, so I apologize in advance for all the fuzz. Just don't know where else to ask this question. Maybe somebody else already run into it.

#### 🤔 Expected Behavior

Was expecting the tool to read all issues in batches of 100 and then exit with status `0` after the last one.

#### 👟 Steps to reproduce

```
git clone git@github.com:mre/rfcs.git
cd rfcs
GITHUB_TOKEN=<token> cargo run
```

#### 🌍 Your environment

hubcaps version: 0.5.0

**Comment by dwijnand** [comment]
I've found `.wait()` just _doesn't_ work.  I'm not sure why, though.

Try using `.iter().collect().map(move |comments| (issue, comments))` instead.

**Comment by mre** [comment]
That did the trick. 🎉 
For *future* reference (see what I did there? 😆 ): 

Before:

```rust
pub fn rfcs(self) -> Stream<Rfc> {
    Box::new(
        self.conn
            .repo(self.owner.clone(), self.repo.clone())
            .issues()
            .iter(
                &IssueListOptions::builder()
                    .per_page(100)
                    .state(State::All)
                    .build(),
            )
            .and_then(move |issue| {
                // println!("Crawling {}", issue.number);
                let comments: Result<Comments, _> = self
                    .conn
                    .repo(self.owner.clone(), self.repo.clone())
                    .issues()
                    .get(issue.number)
                    .comments()
                    .list(&CommentListOptions::builder().build())
                    .wait();
                Ok((issue, comments?))
            })
            .and_then(|(issue, comments)| Ok(Rfc::new(issue, comments))),
    )
}
```

After:

```rust
pub fn rfcs(self) -> Stream<Rfc> {
    Box::new(
        self.conn
            .repo(self.owner.clone(), self.repo.clone())
            .issues()
            .iter(
                &IssueListOptions::builder()
                    .per_page(100)
                    .state(State::All)
                    .build(),
            )
            .and_then(move |issue| {
                self.conn
                    .repo(self.owner.clone(), self.repo.clone())
                    .issues()
                    .get(issue.number)
                    .comments()
                    .list(&CommentListOptions::builder().build())
                    .map(|comment| (issue, comment))
            })
            .and_then(|(issue, comments)| Ok(Rfc::new(issue, comments))),
    )
}
```

In hindsight, I could have noticed earlier, as this limitation for `wait` was [mentioned in the documentation](https://docs.rs/futures/0.1.25/futures/future/trait.Future.html#method.wait):

> Note: This method is not appropriate to call on event loops or similar I/O situations because it will prevent the event loop from making progress (this blocks the thread). This method should only be called when it's guaranteed that the blocking work associated with this future will be completed by another thread.

I gotta learn thinking in `Future`s instead of `Result`s.

Thanks for your help @dwijnand; much appreciated.
