### ISSUE TITLE
Replace hyper with reqwest?

### ISSUE THREAD

**Issue by nickelc** [softprops/hubcaps#210]
Since `reqwest 0.9` is based on `hyper 0.12` and offers a stable [async client](https://docs.rs/reqwest/0.9.9/reqwest/async/index.html) wouldn't it useful to replace the hyper client with reqwest.
#### Benefits:
- cleaner code with the removed type parameters
- redirects handled by reqwest
- proxy support
- rustls support

the changes are straightforward: https://github.com/nickelc/hubcaps/tree/reqwest

**Comment by dwijnand** [comment]
That diff looks like all win to me, except for the `jsonwebtoken` dependency.

**Comment by softprops** [comment]
+timeouts. I'd be up open to a pr for this

**Comment by nickelc** [comment]
> That diff looks like all win to me, except for the `jsonwebtoken` dependency.

i know. `jsonwebtoken 6` from the `next` branch is required at the moment because of its `ring` dependency and the requirements of the reqwest deps.
next version is on the way: https://github.com/Keats/jsonwebtoken/pull/75

> +timeouts.

?
