### ISSUE TITLE
Split response structs into separate crate?

### ISSUE THREAD

**Issue by jasonwhite** [softprops/hubcaps#217]
What do you guys think about splitting all of the response structs (e.g., `User`, `Repo`, or `Pull`) into a separate crate? Such a crate would only implement (de)serialization. This would allow more sharing among other crates and can be tested separately.

I have a bunch of structs for the Events API that I plan on open-sourcing soon that could go into it.

I can get this going. Just wanted to know if there is interest (or if this has already been done).

**Comment by softprops** [comment]
@jasonwhite I'd be open to something like that.

**Comment by jasonwhite** [comment]
I'll get this started. I'll post updates here as I have them. Closing for now since this isn't an actionable issue for hubcaps yet.

**Comment by jasonwhite** [comment]
Here's a first pass: https://github.com/jasonwhite/github-types
