### ISSUE TITLE
Switch to std::future::Future

### ISSUE THREAD

**Issue by keirlawson** [softprops/hubcaps#229]
## 💡 Feature description
It would be great if this library could be made ready for async/await as I think that would make it easier for people to use.  Moving to the standard library Futures seems like the best way to do this and I believe there is already an alpha version of Tokio that supports this.

If this is considered desirable I'd be up for helping out with the effort :)

**Comment by softprops** [comment]
We'll get this for free when hyper publishes a stable release. This lib returns futures directly from hyper. You may be able to leverage some of the futures alpha 3 compat interfaces allowing ton to adapt between futures crate types and std lib

**Comment by shepmaster** [comment]
Hyper 0.13 has been published (and a matching hyper-tls). It appears that this library needs to update the version constraints:

```
hyper v0.12.35
├── hubcaps v0.5.0
└── hyper-tls v0.3.2
    └── hubcaps v0.5.0 (*)
```

**Comment by keirlawson** [comment]
Looks like a compatible version of reqwest is still pending release however

**Comment by shepmaster** [comment]
Reqwest 0.10.0 has been published.

**Comment by johanneskoester** [comment]
Any update on this?

**Comment by softprops** [comment]
This was fixed in https://github.com/softprops/hubcaps/pull/254 and will go out in the next release which I hope to put together this weekend
