### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by keirlawson** [softprops/hubcaps#230]
It would be great to get a version cut that includes recently added functionality that is presently on master.  Are there any particular things blocking this that I could take a look at? The planned API changes mentioned in the README?

**Comment by jessfraz** [comment]
+1 here, would love to see a new version pushed to crates.io!

**Comment by softprops** [comment]
Sorry about that folks. I'll try to make that happen this week.

**Comment by softprops** [comment]
Quick update here. Since this release has some breaking changes I'm doing some long neglected house chores. My goal is to get this out this weekend. Thank you for your patience

**Comment by softprops** [comment]
okay folks. sorry for the delay 

I published 0.6 https://crates.io/crates/hubcaps which should include these changes https://github.com/softprops/hubcaps/blob/master/CHANGELOG.md#060

I invested a bit in making releases as easy as a `git push origin tag` to make it a bit easer to make a release in the future which means I should be able to do this more often

thank you for your patience!
