### ISSUE TITLE
Credentials::Token shouldn't use the default Debug

### ISSUE THREAD

**Issue by grahamc** [softprops/hubcaps#241]
In hubcaps 0.5.0, `Credentials::Token` implements the default Debug implementation, which leaks the token:

```
Token("xxxxxxxxxxxxxx")        
```

Instead, I think it would be safer for the Token to have a custom Debug implementation which elides the specific Token data.

If this makes sense and you agree, I will send a PR.

**Comment by softprops** [comment]
Totally makes sense to me. Nice catch
