### ISSUE TITLE
`missing field` error

### ISSUE THREAD

**Issue by badboy** [softprops/hubcaps#31]
(Same as reported via Twitter)

We're using Hubcaps to create releases: https://github.com/semantic-rs/semantic-rs/blob/9d833599126b012485cf8c083c488e7cd41ed997/src/github.rs

The code runs after tests on Travis, where it sometimes fails with 

```
GitHub(Codec(Syntax(missing field "field", 1, 132)))
```
Link: https://travis-ci.org/badboy/test-project/jobs/118362428#L771

I was not able to reproduce it locally (yet). The build runs with `RUST_LOG=debug`, but no Hubcaps logs are shown (didn't check if there are some in the code path we're triggering).

Seems like that `field` field belongs to `FieldErr` struct, but I don't know where it comes from at the moment.
The Git tag is already pushed when that release happens. 
The error does not happen everytime. Some builds run just fine.

Any idea what's causing this or how we could debug this further?

**Comment by badboy** [comment]
Seems like it is created here (as part of `ClientError`): https://github.com/softprops/hubcaps/blob/a2af9488810c256aef7509182ab9634fbaf680e2/src/lib.rs#L250

Above is a `debug!` line, so in theory I should see logging statements.

**Comment by badboy** [comment]
D'oh! Figured I should actually enable env_logger in my own crate.

**Comment by badboy** [comment]
Ok, figured it out now.
https://travis-ci.org/badboy/test-project/jobs/118373494#L777
The body contains: 

```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Release",
      "code": "custom",
      "message": "Published releases must have a valid tag"
    }
  ]
}
```

Not sure if the GitHub API is wrong (or wrong documented), but Hubcaps might need to safe-guard against that.

And regarding my problem: it's likely a race condition.

**Comment by softprops** [comment]
Ah, thanks for all the specific info. I think just need to make [FieldError.field](https://github.com/softprops/hubcaps/blob/master/src/rep.rs.in#L6) and Optional String. The original structure was based on the info [here](https://developer.github.com/v3/#client-errors). I'll make that change and do a bit more testing this weekend. It looks like there are more keys in json returned that I'm deserializing. Looks like each field message can have it's own _optional_ message as well. 

I'll try to get this squared away this coming weekend.

That's for reporting and thanks for the debugging work!

**Comment by badboy** [comment]
I send a tweet to GitHub for clarification as to me the API description reads like there should always be a `field` field. No answer yet.

**Comment by softprops** [comment]
Yea it seems like there would be a `field` with a value of `tag` in this case. Either way I want to make hubcaps a little more fail a little more gracefully for these cases :)

**Comment by badboy** [comment]
Thank you!

**Comment by softprops** [comment]
@badboy wanted to give you a heads up I pushed a release ( [0.2.1](https://github.com/softprops/hubcaps/blob/0.2.1/CHANGELOG.md#021) ) with the fix for this

**Comment by badboy** [comment]
Thanks again!
