### ISSUE TITLE
Add support for search

### ISSUE THREAD

**Issue by mkroman** [softprops/hubcaps#50]
Hi.

It doesn't seem like hubcaps supports the search API.

It would be useful to be able to search repositories, users, issues, etc.

For more information, see https://developer.github.com/v3/search/

**Comment by softprops** [comment]
That's a good point @mkroman. I can look into this

**Comment by softprops** [comment]
@mkroman I published a new version of hubcaps initial support for searching issues. im going to open up separate specific issues for support for searching code and repos
