### ISSUE TITLE
look into derive-builder

### ISSUE THREAD

**Issue by softprops** [softprops/hubcaps#84]
alot of the code contained in this repo targets building structs for requests parameters
https://github.com/colin-kiegel/rust-derive-builder represents a path for replacing that with something generated which should result in a smaller more maintainable code base

**Comment by dwijnand** [comment]
Is this still the plan, @softprops?

If so I might just look into this.

**Comment by softprops** [comment]
It would likely save a lot of manually written "builder" code at the moment for building up requests.  I was deferring this until I had a few things worth making a breaking change for to make a breaking change worth it. A new version of hyper was just released so it now may be a fine time.

**Comment by dwijnand** [comment]
Still no sign of a tool to mechanically check if a change is breaking, right? I'm wondering how much can be converted to derive-builder without breaking compatibility.

**Comment by softprops** [comment]
Trimming issues. Closing for now. Will reopen when there's more motivation
