### ISSUE TITLE
Support `https://api.github.com/user`?

### ISSUE THREAD

**Issue by dpc** [softprops/hubcaps#89]
I need to get information about the signed-in user, and I can't find a an API to do it. If I write a PR, will it be accepted?

It seems there are more information in the response to this endpoint, then `User` currently have. Should I create a new structure, or extend the existing one somehow? How should I name them?

**Comment by softprops** [comment]
Pulls are absolutely welcome. In looked at https://developer.github.com/v3/users/#get-the-authenticated-user and I can see the structure returned has some private info not available in the user structure returned in other apis. 

The pattern is typically to define a new method associated with the github struct https://github.com/softprops/hubcaps/blob/master/src/lib.rs for an exported interface in another module.

This might look something like.

```rust
let user = github.users().authenticated().unwrap()
```

A users mod currently exists but lacks query interfaces https://github.com/softprops/hubcaps/blob/master/src/users/mod.rs but you can infer what one might look like based on the other mods.

As for type name maybe AuthenicatedUser?

Let me know if you get stuck.

**Comment by dpc** [comment]
Fixed in #90 and #91
