### ISSUE TITLE
No issue/bug: Thumbs up for the library!

### ISSUE THREAD

**Issue by SirVer** [softprops/hubcaps#92]
Hey there, not an issue or bug, but I just wanted to say: good job on the API design of the library.

I tried to use it in a merge bot for https://github.com/googlecartographer/ and it is a joy to use. Unfortunately it is not complete enough for my purposes yet (around status information for pull requests), so I'll write the tool in go for now. Please keep it up and it will be a fine library in the future!

**Comment by SirVer** [comment]
Feel free to close this right away again.

**Comment by softprops** [comment]
@SirVer jus now see thing this. Very cool!
